version: '3'

volumes:
    mercure_data:
    mercure_config:

services:
    mercure:
        container_name: mercure
        hostname: mercure
        image: dunglas/mercure
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        environment:
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_PUBLIC_KEY}
            MERCURE_PUBLISHER_JWT_ALG: ${MERCURE_JWT_ALGORITHM}
            MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_PUBLIC_KEY}
            MERCURE_SUBSCRIBER_JWT_ALG: ${MERCURE_JWT_ALGORITHM}
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins ${CORS_ALLOWED_ORIGINS} /
                publish_origins ${MERCURE_PUBLISH_ALLOWED_ORIGINS} /
                demo ${MERCURE_DEMO} /
                anonymous ${MERCURE_ANONYMOUS}
        command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
        volumes:
            - mercure_data:/data
            - mercure_config:/config
            - ./conf/Caddyfile.dev:/etc/caddy/Caddyfile.dev
            - ./conf/Caddyfile:/etc/caddy/Caddyfile
            - ./logs/logs:/var/log/caddy:rw
        env_file:
            - ./.env
